[package]
name = "birdnet"
version = "0.1.0"
edition = "2021"

[dependencies]
async-std = "1.10.0"
birdnet-derive = { path = "../birdnet-derive" }
num-derive = "0.3.3"
num-traits = "0.2.14"
bytes = "1.1.0"
paste = "1.0.6"
