[package]
name = "birdnet_derive"
version = "0.1.0"
authors = ["WhiteGrouse <39170892+WhiteGrouse@users.noreply.github.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.18"
syn = "1.0.31"
quote = "1.0.7"
